all: hierarchical.out network.out

hierarchical.out: hierarchical.cpp
	g++ -Wall -pedantic -o hierarchical.out hierarchical.cpp

network.out: network.cpp
	g++ -Wall -pedantic -o network.out network.cpp
