all: 1.out 2.out 3.out 4.out

1.out: 1.cpp
	g++ -Wall -pedantic -o 1.out 1.cpp

2.out: 2.cpp
	g++ -Wall -pedantic -o 2.out 2.cpp

3.out: 3.cpp
	g++ -Wall -pedantic -o 3.out 3.cpp

4.out: 4.cpp
	g++ -Wall -pedantic -o 4.out 4.cpp
