all: calc_entropy.out generate_file.out

calc_entropy.out: calc_entropy.cpp
	g++ -Wall -pedantic -o calc_entropy.out calc_entropy.cpp

generate_file.out: generate_file.cpp
	g++ -Wall -pedantic -o generate_file.out generate_file.cpp
